# Generated by Django 4.0.1 on 2022-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
