# Generated by Django 4.0.1 on 2022-02-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(help_text='Recommended Size 350X260px', upload_to='blog'),
        ),
    ]
