# Generated by Django 4.0.1 on 2022-02-28 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='real_image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Used Inside a Blog', upload_to='detail_blog'),
            preserve_default=False,
        ),
    ]
