# Generated by Django 4.0.1 on 2022-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, verbose_name='email_address')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
